[tool.poetry]
name = "{{ cookiecutter.module_name }}"
version = "{{ cookiecutter.version }}"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

include = [
    # Native build inputs required when rebuilding from the source distribution.
    { path = "CMakeLists.txt", format = "sdist" },
    { path = "CMakePresets.json", format = "sdist" },
    { path = "build.py", format = "sdist" },
    { path = "vcpkg.json", format = "sdist" },
    { path = "vcpkg-configuration.json", format = "sdist" },
    { path = "vcpkg-ports/gtest/*", format = "sdist" },
    { path = "cpp/CMakeLists.txt", format = "sdist" },
    { path = "cpp/bindings/*.*", format = "sdist" },
    { path = "cpp/include/{{ cookiecutter.module_name }}_core/*.*", format = "sdist" },
    { path = "cpp/src/*.*", format = "sdist" },
    { path = "examples/cpp/*.*", format = "sdist" },
    { path = "tests/cpp/*.*", format = "sdist" },
    # C extensions must be included in the wheel distribution.
    { path = "src/{{ cookiecutter.module_name }}/*.pyd", format = "wheel" },
    { path = "src/{{ cookiecutter.module_name }}/*.so", format = "wheel" },
]
exclude = [
    "cpp/*",
]

[tool.poetry.build]
generate-setup-file = false
script = "build.py"

[tool.poetry.dependencies]
python = "{{ cookiecutter.python_version }}"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core", "cmake", "ninja"]
build-backend = "poetry.core.masonry.api"
